/**
 * @page misc Miscellaneous libraries
 *
 * These files are independent of NeoMutt, but haven't yet been placed in a library.
 *
 * | File           | Description           |
 * | :------------- | :-------------------- |
 * | envelope.c     | @subpage envelope     |
 * | history.c      | @subpage history      |
 * | mutt_logging.c | @subpage mutt_logging |
 * | tags.c         | @subpage tags         |
 */
